version: '3'

services:
  # MongoDB for Graylog metadata
  mongo:
    image: mongo:4.2
    networks:
      - graylog

  # Elasticsearch for Graylog storage
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - graylog
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g

  # Graylog server
  graylog:
    image: graylog/graylog:4.0
    environment:
      - GRAYLOG_PASSWORD_SECRET=YourSecretPass # Use a secure password secret
      - GRAYLOG_ROOT_PASSWORD_SHA2=YourSHA2ofSecretPass # SHA2 (256) hash of your password
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - mongo
      - elasticsearch
    networks:
      - graylog
    ports:
      - "9000:9000"   # Graylog web interface
      - "12201:12201/udp"  # GELF UDP port for logging

  # FastAPI application service
  fastapi-app:
    image: wolfram177/fastapi-backend-app:latest
    networks:
      - graylog
    ports:
      - "8000:8000" # Expose FastAPI port
    depends_on:
      - graylog

networks:
  graylog:
    driver: bridge
